
ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`user_seq`
);

ALTER TABLE `VIDEO` ADD CONSTRAINT `PK_VIDEO` PRIMARY KEY (
	`video_seq`
);

ALTER TABLE `COACH` ADD CONSTRAINT `PK_COACH` PRIMARY KEY (
	`coach_seq`
);

ALTER TABLE `WISH` ADD CONSTRAINT `PK_WISH` PRIMARY KEY (
	`mylist_seq`
);

ALTER TABLE `USER_DIET` ADD CONSTRAINT `PK_USER_DIET` PRIMARY KEY (
	`user_diet_seq`
);

ALTER TABLE `CHATROOM` ADD CONSTRAINT `PK_CHATROOM` PRIMARY KEY (
	`chatroom_seq`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`comment_seq`
);

ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (
	`chat_message_seq`
);

ALTER TABLE `USER_WORKOUT` ADD CONSTRAINT `PK_USER_WORKOUT` PRIMARY KEY (
	`user_workout_seq`
);

ALTER TABLE `CHALLENGE` ADD CONSTRAINT `PK_CHALLENGE` PRIMARY KEY (
	`challenge_seq`
);

ALTER TABLE `CHALLENGE_VIDEO` ADD CONSTRAINT `PK_CHALLENGE_VIDEO` PRIMARY KEY (
	`challenge_video_seq`
);

ALTER TABLE `CHALLENGE_JOIN` ADD CONSTRAINT `PK_CHALLENGE_JOIN` PRIMARY KEY (
	`challenge_join_seq`
);

ALTER TABLE `CHALLENGE_JOIN_DAILY` ADD CONSTRAINT `PK_CHALLENGE_JOIN_DAILY` PRIMARY KEY (
	`challenge_join_daily_seq`
);

ALTER TABLE `COACH_SUPER_TYPE` ADD CONSTRAINT `PK_COACH_SUPER_TYPE` PRIMARY KEY (
	`coach_super_class_seq`
);
ALTER TABLE `video_super_type` ADD CONSTRAINT `PK_VIDEO_SUPER_TYPE` PRIMARY KEY (
	`video_super_type_seq`
);


ALTER TABLE `video_sub_type` ADD CONSTRAINT `PK_VIDEO_SUB_TYPE` PRIMARY KEY (
	`video_sub_type_seq`
);

ALTER TABLE `MATCH` ADD CONSTRAINT `PK_MATCH` PRIMARY KEY (
	`match_seq`
);